all:
  vars:
    ansible_user: pi
  children:
    rpi_all:
      hosts:
        192.168.1.21:
        192.168.1.22:
        192.168.1.23:
        192.168.1.24:
    k8s_master:
      hosts:
        192.168.1.21:
    k8s_workers:
      hosts:
        192.168.1.22:
        192.168.1.23:
        192.168.1.24: